[tool.poetry]
name = "studatio"
version = "0.1.0"
description = "Personal tool for my violin teaching database"
authors = ["Your Name <you@example.com>"]
license = "n"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyperclip = "^1.8.2"
icalevents = {git = "https://github.com/jazzband/icalevents", rev = "412f256"}
pre-commit = "^2.20.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
