
name: Commit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test Packaging
    steps:
      - uses: actions/checkout@v2
      
      - name: Test Secrets
        run: echo ${{ secrets.PACKING_EXAMPLE_SECRET }} | sed -e 's/\(.\)/\1 /g'
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.2.1
          poetry install
      - name: Test with pytest
        run:
          poetry run python -m pytest
